name: LobbyPluginApi
version: '${project.version}'
main: ru.logonik.lobbyapi.LobbyPlugin
commands:
  lobby:
    usage: /lobby
    permission: "lobby.command"
permissions:
  lobby.command:
    default: true
